# Generated by Django 3.2.9 on 2021-11-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='ppt',
            field=models.FileField(blank=True, default='ppt', upload_to='ppt/', verbose_name='Presentation'),
        ),
    ]
